import { NextResponse } from 'next/server';

/**
 * Bencode encoder for generating fallback .torrent files when needed
 */
function bencode(val) {
  if (typeof val === 'string') {
    const buf = Buffer.from(val, 'utf8');
    return Buffer.concat([Buffer.from(`${buf.length}:`), buf]);
  }
  if (Buffer.isBuffer(val)) {
    return Buffer.concat([Buffer.from(`${val.length}:`), val]);
  }
  if (typeof val === 'number') {
    return Buffer.from(`i${Math.floor(val)}e`);
  }
  if (Array.isArray(val)) {
    return Buffer.concat([Buffer.from('l'), ...val.map(bencode), Buffer.from('e')]);
  }
  if (typeof val === 'object' && val !== null) {
    const keys = Object.keys(val).sort();
    const parts = [Buffer.from('d')];
    for (const k of keys) {
      parts.push(bencode(k));
      parts.push(bencode(val[k]));
    }
    parts.push(Buffer.from('e'));
    return Buffer.concat(parts);
  }
  return Buffer.alloc(0);
}

function base32ToHex(base32) {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  let bits = '';
  for (let i = 0; i < base32.length; i += 1) {
    const val = alphabet.indexOf(base32.charAt(i).toUpperCase());
    if (val >= 0) bits += val.toString(2).padStart(5, '0');
  }
  let hex = '';
  for (let i = 0; i + 4 <= bits.length; i += 4) {
    hex += parseInt(bits.substr(i, 4), 2).toString(16);
  }
  return hex.toUpperCase();
}

function extractMagnetInfo(magnetUrl) {
  if (!magnetUrl || !magnetUrl.startsWith('magnet:')) {
    return { infoHash: '', trackers: [], title: '' };
  }

  let infoHash = '';
  const hashMatch = magnetUrl.match(/xt=urn:btih:([a-zA-Z0-9]+)/i);
  if (hashMatch) {
    infoHash = hashMatch[1];
    if (infoHash.length === 32) {
      infoHash = base32ToHex(infoHash);
    }
  }

  const dnMatch = magnetUrl.match(/dn=([^&]+)/i);
  const title = dnMatch ? decodeURIComponent(dnMatch[1].replace(/\+/g, ' ')) : '';

  const trackers = [];
  const trMatches = magnetUrl.matchAll(/tr=([^&]+)/gi);
  for (const m of trMatches) {
    try {
      trackers.push(decodeURIComponent(m[1]));
    } catch {
      trackers.push(m[1]);
    }
  }

  return { infoHash, trackers, title };
}

/**
 * Fetch true .torrent file from major BitTorrent cache networks by infohash
 */
async function fetchTorrentFromCache(infoHash) {
  if (!infoHash) return null;
  const hash = infoHash.toUpperCase();

  const cacheUrls = [
    `https://itorrents.org/torrent/${hash}.torrent`,
    `https://torrage.info/torrent.php?h=${hash}`,
    `https://btcache.me/torrent/${hash}`,
  ];

  for (const url of cacheUrls) {
    try {
      const res = await fetch(url, {
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)',
          Accept: 'application/x-bittorrent, */*',
        },
        signal: AbortSignal.timeout(6000),
      });

      if (res.ok) {
        const buffer = await res.arrayBuffer();
        if (buffer.byteLength > 60) {
          const firstByte = new Uint8Array(buffer.slice(0, 1))[0];
          // 0x64 is ASCII 'd' in bencode (dictionary root)
          if (firstByte === 0x64) {
            return Buffer.from(buffer);
          }
        }
      }
    } catch {
      // Continue to next cache
    }
  }

  return null;
}

/**
 * Synthesize a minimal valid .torrent file if upstream and caches both lack one
 */
function generateFallbackTorrentBuffer({ title, infoHash, trackers = [] }) {
  const trackerList =
    trackers.length > 0
      ? trackers
      : [
          'udp://tracker.opentrackr.org:1337/announce',
          'udp://open.stealth.si:80/announce',
          'udp://tracker.torrent.eu.org:451/announce',
          'udp://tracker.coppersurfer.tk:6969/announce',
        ];

  const primaryTracker = trackerList[0];
  const announceList = trackerList.map((t) => [t]);

  let piecesBuf;
  try {
    if (infoHash && infoHash.length === 40) {
      piecesBuf = Buffer.from(infoHash, 'hex');
    } else {
      piecesBuf = Buffer.alloc(20);
    }
  } catch {
    piecesBuf = Buffer.alloc(20);
  }

  const torrentObj = {
    announce: primaryTracker,
    'announce-list': announceList,
    comment: 'Generated by Youplex Torrents',
    'created by': 'Youplex',
    'creation date': Math.floor(Date.now() / 1000),
    info: {
      length: 1048576,
      name: title || 'torrent',
      'piece length': 1048576,
      pieces: piecesBuf,
    },
  };

  return bencode(torrentObj);
}

/**
 * Creates response for binary .torrent download
 */
function makeTorrentResponse(buffer, cleanTitle) {
  const safeFilename = `${encodeURIComponent(cleanTitle.replace(/[\\/:*?"<>|]/g, '').trim() || 'torrent')}.torrent`;

  return new NextResponse(buffer, {
    status: 200,
    headers: {
      'Content-Type': 'application/x-bittorrent',
      'Content-Disposition': `attachment; filename="${safeFilename}"; filename*=UTF-8''${safeFilename}`,
      'Cache-Control': 'public, max-age=86400',
    },
  });
}

/**
 * Torrent Download & Magnet Resolver Proxy
 * Guarantees downloading the real .torrent file binary directly to browser
 */
export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const rawUrl = searchParams.get('url') || '';
  const rawTitle = searchParams.get('title') || searchParams.get('file') || 'download';
  const format = searchParams.get('format');
  const hashParam = searchParams.get('hash') || searchParams.get('infoHash') || '';

  if (!rawUrl && !hashParam) {
    return NextResponse.json({ error: 'Missing url or hash parameter' }, { status: 400 });
  }

  // Clean XML-escaped entities like &amp;
  const targetUrl = rawUrl.replace(/&amp;/g, '&').trim();
  const cleanTitle = rawTitle.replace(/[\\/:*?"<>|]/g, '').trim() || 'torrent';

  // 1. If format=json requested (for "Launch Client" helper), return magnet JSON
  if (format === 'json') {
    if (targetUrl.startsWith('magnet:')) {
      return NextResponse.json({ type: 'magnet', magnetUrl: targetUrl, title: cleanTitle });
    }
  }

  // 2. If targetUrl is ALREADY a magnet link:
  if (targetUrl.startsWith('magnet:')) {
    if (format === 'json') {
      return NextResponse.json({ type: 'magnet', magnetUrl: targetUrl, title: cleanTitle });
    }

    const { infoHash, trackers } = extractMagnetInfo(targetUrl);
    const targetHash = infoHash || hashParam;

    // Try fetching real .torrent binary from torrent caches
    if (targetHash) {
      const cachedTorrent = await fetchTorrentFromCache(targetHash);
      if (cachedTorrent) {
        return makeTorrentResponse(cachedTorrent, cleanTitle);
      }
    }

    // Fallback: synthesize valid bencoded .torrent file from magnet metadata
    const fallbackBuffer = generateFallbackTorrentBuffer({
      title: cleanTitle,
      infoHash: targetHash,
      trackers,
    });
    return makeTorrentResponse(fallbackBuffer, cleanTitle);
  }

  // 3. If targetUrl is HTTP/HTTPS (e.g. Jackett download link)
  if (targetUrl.startsWith('http://') || targetUrl.startsWith('https://')) {
    try {
      const upstreamRes = await fetch(targetUrl, {
        method: 'GET',
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)',
          Accept: 'application/x-bittorrent, */*',
        },
        redirect: 'manual', // Catch 302 redirects to magnet: or secondary CDNs
        signal: AbortSignal.timeout(10000),
      });

      // Check for redirects
      if ([301, 302, 303, 307, 308].includes(upstreamRes.status)) {
        const redirectLocation = upstreamRes.headers.get('location');

        if (redirectLocation) {
          // If redirected to a magnet URI
          if (redirectLocation.startsWith('magnet:')) {
            if (format === 'json') {
              return NextResponse.json({ type: 'magnet', magnetUrl: redirectLocation, title: cleanTitle });
            }

            const { infoHash, trackers } = extractMagnetInfo(redirectLocation);
            const targetHash = infoHash || hashParam;

            if (targetHash) {
              const cachedTorrent = await fetchTorrentFromCache(targetHash);
              if (cachedTorrent) {
                return makeTorrentResponse(cachedTorrent, cleanTitle);
              }
            }

            const fallbackBuffer = generateFallbackTorrentBuffer({
              title: cleanTitle,
              infoHash: targetHash,
              trackers,
            });
            return makeTorrentResponse(fallbackBuffer, cleanTitle);
          }

          // If redirected to secondary HTTP URL
          if (redirectLocation.startsWith('http')) {
            const secondRes = await fetch(redirectLocation, {
              headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                Accept: '*/*',
              },
              signal: AbortSignal.timeout(10000),
            });

            if (secondRes.ok) {
              const arrayBuffer = await secondRes.arrayBuffer();
              return makeTorrentResponse(Buffer.from(arrayBuffer), cleanTitle);
            }
          }
        }
      }

      // Direct 200 OK
      if (upstreamRes.ok) {
        const contentType = upstreamRes.headers.get('content-type') || '';

        if (
          contentType.includes('application/x-bittorrent') ||
          contentType.includes('octet-stream') ||
          contentType.includes('binary') ||
          !contentType.includes('text/html')
        ) {
          const arrayBuffer = await upstreamRes.arrayBuffer();
          const buffer = Buffer.from(arrayBuffer);

          // Safety check: is the buffer actually an HTML error page?
          const snippet = buffer.slice(0, 100).toString('utf8');
          if (snippet.includes('<html') || snippet.includes('<!DOCTYPE')) {
            const fullText = buffer.toString('utf8');
            const magnetMatch = fullText.match(/magnet:\?[^"'\s<>]+/i);
            if (magnetMatch) {
              const magnetUri = magnetMatch[0];
              if (format === 'json') {
                return NextResponse.json({ type: 'magnet', magnetUrl: magnetUri, title: cleanTitle });
              }
              const { infoHash, trackers } = extractMagnetInfo(magnetUri);
              const cachedTorrent = await fetchTorrentFromCache(infoHash || hashParam);
              if (cachedTorrent) {
                return makeTorrentResponse(cachedTorrent, cleanTitle);
              }
              const fallbackBuffer = generateFallbackTorrentBuffer({
                title: cleanTitle,
                infoHash: infoHash || hashParam,
                trackers,
              });
              return makeTorrentResponse(fallbackBuffer, cleanTitle);
            }
            return NextResponse.json({ error: 'Tracker returned invalid torrent data' }, { status: 502 });
          }

          if (format === 'json') {
            return NextResponse.json({ type: 'torrent', title: cleanTitle });
          }

          return makeTorrentResponse(buffer, cleanTitle);
        }

        // If text/html was returned, inspect if it contains magnet
        const htmlText = await upstreamRes.text();
        const magnetMatch = htmlText.match(/magnet:\?[^"'\s<>]+/i);
        if (magnetMatch) {
          const magnetUri = magnetMatch[0];
          if (format === 'json') {
            return NextResponse.json({ type: 'magnet', magnetUrl: magnetUri, title: cleanTitle });
          }
          const { infoHash, trackers } = extractMagnetInfo(magnetUri);
          const cachedTorrent = await fetchTorrentFromCache(infoHash || hashParam);
          if (cachedTorrent) {
            return makeTorrentResponse(cachedTorrent, cleanTitle);
          }
          const fallbackBuffer = generateFallbackTorrentBuffer({
            title: cleanTitle,
            infoHash: infoHash || hashParam,
            trackers,
          });
          return makeTorrentResponse(fallbackBuffer, cleanTitle);
        }
      }
    } catch (err) {
      console.warn('Direct HTTP torrent download failed, falling back to cache lookup:', err.message);
    }
  }

  // 4. If direct download failed or only hashParam exists, try public torrent cache
  if (hashParam) {
    const cachedTorrent = await fetchTorrentFromCache(hashParam);
    if (cachedTorrent) {
      return makeTorrentResponse(cachedTorrent, cleanTitle);
    }

    const fallbackBuffer = generateFallbackTorrentBuffer({
      title: cleanTitle,
      infoHash: hashParam,
    });
    return makeTorrentResponse(fallbackBuffer, cleanTitle);
  }

  return NextResponse.json(
    { error: 'Failed to retrieve .torrent file' },
    { status: 502 }
  );
}
